"""baseline_existing_schema

Revision ID: 4ff5b5898f71
Revises:
Create Date: 2026-04-23 16:05:20.201877

Creates the four core tables (packs, tools, requests, memory_events) at
their pre-`tool_type` shape. Revision 7bdb4433afa8 adds the tool_type
column on top of this baseline.

**Idempotency guard.** When Alembic was bootstrapped on 2026-04-24 (Fix
Day 1), this migration was autogenerated as a zero-ops stub because it
ran against a live dev DB that already held the tables from the prior
`Base.metadata.create_all()` world. The live DB was then
`alembic stamp head`'d at this revision. A fresh clone running
`alembic upgrade head` would therefore have reached 7bdb4433afa8 with no
tools table present, and the `ALTER TABLE tools ADD COLUMN tool_type`
step would crash. The Fix Day 2 drift test caught that exact failure —
see DECISIONS `[2026-04-25 Fix Day 2]` — and the fix is this rewritten
baseline: real `op.create_table` ops wrapped in a `has_table('tools')`
guard so stamped-forward DBs remain a no-op while fresh installs get the
tables they need.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4ff5b5898f71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the four core tables if absent.

    A live DB stamped at this revision on 2026-04-24 already holds these
    tables — the `has_table('tools')` check short-circuits so re-running
    the chain there stays a no-op. A fresh install sees an empty DB,
    falls through the guard, and gets the full baseline schema.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("tools"):
        return

    op.create_table(
        "packs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transport", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packs_slug"), "packs", ["slug"], unique=True)
    op.create_index(op.f("ix_packs_status"), "packs", ["status"], unique=False)

    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pack_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("install_method", sa.String(length=32), nullable=True),
        sa.Column("is_in_manifest", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pack_id"], ["packs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tools_slug"), "tools", ["slug"], unique=True)
    op.create_index(op.f("ix_tools_pack_id"), "tools", ["pack_id"], unique=False)
    op.create_index(op.f("ix_tools_category"), "tools", ["category"], unique=False)
    op.create_index(
        op.f("ix_tools_is_in_manifest"), "tools", ["is_in_manifest"], unique=False
    )
    op.create_index(op.f("ix_tools_is_active"), "tools", ["is_active"], unique=False)

    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("folder", sa.String(length=32), nullable=False),
        sa.Column("tool_name", sa.String(length=256), nullable=False),
        sa.Column("tool_slug", sa.String(length=128), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.String(length=16), nullable=True),
        sa.Column("is_discovered", sa.Boolean(), nullable=False),
        sa.Column("raw_markdown", sa.Text(), nullable=False),
        sa.Column("parsed_data", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requests_filename"), "requests", ["filename"], unique=True
    )
    op.create_index(
        op.f("ix_requests_status"), "requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_requests_folder"), "requests", ["folder"], unique=False
    )
    op.create_index(
        op.f("ix_requests_tool_slug"), "requests", ["tool_slug"], unique=False
    )
    op.create_index(
        op.f("ix_requests_category"), "requests", ["category"], unique=False
    )

    op.create_table(
        "memory_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_events_event_type"),
        "memory_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_events_occurred_at"),
        "memory_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_events_source"),
        "memory_events",
        ["source"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the four core tables in reverse FK order."""
    op.drop_index(op.f("ix_memory_events_source"), table_name="memory_events")
    op.drop_index(op.f("ix_memory_events_occurred_at"), table_name="memory_events")
    op.drop_index(op.f("ix_memory_events_event_type"), table_name="memory_events")
    op.drop_table("memory_events")

    op.drop_index(op.f("ix_requests_category"), table_name="requests")
    op.drop_index(op.f("ix_requests_tool_slug"), table_name="requests")
    op.drop_index(op.f("ix_requests_folder"), table_name="requests")
    op.drop_index(op.f("ix_requests_status"), table_name="requests")
    op.drop_index(op.f("ix_requests_filename"), table_name="requests")
    op.drop_table("requests")

    op.drop_index(op.f("ix_tools_is_active"), table_name="tools")
    op.drop_index(op.f("ix_tools_is_in_manifest"), table_name="tools")
    op.drop_index(op.f("ix_tools_category"), table_name="tools")
    op.drop_index(op.f("ix_tools_pack_id"), table_name="tools")
    op.drop_index(op.f("ix_tools_slug"), table_name="tools")
    op.drop_table("tools")

    op.drop_index(op.f("ix_packs_status"), table_name="packs")
    op.drop_index(op.f("ix_packs_slug"), table_name="packs")
    op.drop_table("packs")
