"""add_tool_type_enum_and_backfill

Revision ID: 7bdb4433afa8
Revises: 4ff5b5898f71
Create Date: 2026-04-23 16:07:21.554006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bdb4433afa8'
down_revision: Union[str, Sequence[str], None] = '4ff5b5898f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_type', sa.Enum('mcp', 'cli', 'http', 'skill', name='tool_type'), nullable=True))
        batch_op.create_index(batch_op.f('ix_tools_tool_type'), ['tool_type'], unique=False)

    # ### end Alembic commands ###

    # Backfill: derive tool_type from install_method so the 4 seeded
    # rows (and any future rows with matching install_method) land
    # populated. mcp-server → mcp; apt / pip-user → cli.
    op.execute(
        "UPDATE tools SET tool_type = 'mcp' WHERE install_method = 'mcp-server'"
    )
    op.execute(
        "UPDATE tools SET tool_type = 'cli' "
        "WHERE install_method IN ('apt', 'pip-user') AND tool_type IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_tool_type'))
        batch_op.drop_column('tool_type')

    # ### end Alembic commands ###
